


eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    enabled: true
    eureka-service-url-poll-interval-seconds: 35

  instance:
    preferIpAddress: true
    lease-renewal-interval-in-seconds: 30
server:
  port:0
spring:
  application:
    name: eclient
