

spring:

  application:
    name: client-service
  sleuth:
    sampler:
      probability: 2.0
  zipkin:
    enabled: true

  config:
    import: "optional:configserver:"
  cloud:
    config:
      enabled: true
      discovery:
        enabled: true
        service-id: config-server
    openfeign:
      circuitbreaker:
        enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    enabled: true
    eureka-service-url-poll-interval-seconds: 35

  instance:
    preferIpAddress: true
    lease-renewal-interval-in-seconds: 30
    instance-id: ${spring.application.name}:${random.uuid}
server:
  port: 0
