server:
  port: 8765

spring:
  application:
    name: gateway-service
  sleuth:
    sampler:
      probability: 2.0
  zipkin:
    enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    enabled: true
    eureka-service-url-poll-interval-seconds: 35

  instance:
    preferIpAddress: true
    lease-renewal-interval-in-seconds: 30